CREATE TABLE "CELL" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FLOOR" INTEGER NOT NULL,
    "CAPACITY" INTEGER NOT NULL
);

CREATE TABLE "PRISONER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "SURNAME" VARCHAR(255) NOT NULL,
    "BORN" DATE
);

CREATE TABLE "SENTENCE" (
    "PRISONERID" BIGINT REFERENCES PRISONER(ID),
	  "CELLID" BIGINT REFERENCES CELL(ID),
    "PUNISHMENT" VARCHAR(255) NOT NULL,
    "STARTDAY" DATE,
    "ENDDAY" DATE
);