
package cz.muni.fi.pv168.gui;

import cz.muni.fi.pv168.common.DBUtils;
import cz.muni.fi.pv168.prison.backend.Cell;
import cz.muni.fi.pv168.prison.backend.CellManager;
import cz.muni.fi.pv168.prison.backend.CellManagerImpl;
import cz.muni.fi.pv168.prison.backend.Prisoner;
import cz.muni.fi.pv168.prison.backend.PrisonerManager;
import cz.muni.fi.pv168.prison.backend.PrisonerManagerImpl;
import cz.muni.fi.pv168.prison.backend.SentenceManager;
import cz.muni.fi.pv168.prison.backend.SentenceManagerImpl;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import javax.sql.DataSource;
import org.apache.commons.dbcp2.BasicDataSource;
import java.util.logging.Logger;
import cz.muni.fi.pv168.prison.backend.Sentence;
import java.time.DateTimeException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
//import javafx.scene.control.Cell;
/**
 *
 * @author Zita
 */
public class PrisonFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrisonFrame
     */
    public PrisonFrame() {
        initComponents();

        PrisonersTableModel model_prisoners = (PrisonersTableModel) jTablePrisoners.getModel();
        CellsTableModel model_cells = (CellsTableModel) jTableCells.getModel();
        SentencesTableModel model_sentences = (SentencesTableModel) jTableSentences.getModel();
        addAllCells(model_cells);
        addAllSentences(model_sentences);
        addAllPrisoners(model_prisoners);
        
    }
    private static final Logger logger = Logger.getLogger(
            PrisonFrame.class.getName());
    private DataSource dataSource = getDatasource();
    private SentenceManager sM = new SentenceManagerImpl(this.dataSource);
    private CellManager cM = new CellManagerImpl(this.dataSource);
    private PrisonerManager pM = new PrisonerManagerImpl(this.dataSource);
    
    private void addAllSentences(SentencesTableModel model_sentences) {
        List<Sentence> ls = sM.findAllSentences();
        
        for (Sentence s : ls) {
            model_sentences.addSentence(s);
        }
    }
    
    private void addAllCells(CellsTableModel model_cells) {
        Cell cell = new Cell(3,2);
        cM.createCell(cell);
        List<Cell> ls = cM.findAllCells();
        
        for (Cell c : ls) {
            model_cells.addCell(c);
        }
    }
    
    private void addAllPrisoners(PrisonersTableModel model_prisoners) {
        /*Prisoner prisoner = new Prisoner("Oldrich", "Konecny", LocalDate.of(1994, 8, 1));
        pM.createPrisoner(prisoner);*/
        List<Prisoner> ls = pM.findAllPrisoners();
        
        for (Prisoner p : ls) {
            model_prisoners.addPrisoner(p);
        }
    }
    
    private DataSource getDatasource() {
        /*
        Properties myConf = new Properties();
        
        try {
            myConf.load(Main.class.getResourceAsStream("src/main/resources/cz/muni/fi/pv168/prison/gui/configuration.properties"));
        } catch (IOException ex) {
            logger.log(Level.SEVERE, "cannot reach configuration.properties file", ex);
        }
        */
        BasicDataSource ds = new BasicDataSource();
        ds.setUrl("jdbc:derby:memory:books;create=true");//myConf.getProperty("jdbc.url"));
        ds.setUsername("makeup");//myConf.getProperty("jdbc.user"));
        ds.setPassword("heslo");//myConf.getProperty("jdbc.password"));
        
        try {
            DBUtils.executeSqlScript(ds,SentenceManager.class.getResource("createTables.sql"));
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "cannot reach createTables.sql", ex);
        }
        return ds;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePrison = new javax.swing.JTabbedPane();
        jPanelPrisoners = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePrisoners = new javax.swing.JTable();
        jButtonCreatePrisoner = new javax.swing.JButton();
        jLabelPrisoners = new javax.swing.JLabel();
        jTextFieldPrisonerCreateName = new javax.swing.JTextField();
        jTextFieldPrisonerCreateSurname = new javax.swing.JTextField();
        jButtonDeletePrisoner = new javax.swing.JButton();
        jTextFieldPrisonerUpdateName = new javax.swing.JTextField();
        jTextFieldPrisonerUpdateSurname = new javax.swing.JTextField();
        jButtonUpdatePrisoner = new javax.swing.JButton();
        jComboBoxSentencePunishment = new javax.swing.JComboBox<>();
        jButtonCreateSentence = new javax.swing.JButton();
        jLabelCells = new javax.swing.JLabel();
        jComboBoxCreateCellFloor = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCells = new javax.swing.JTable();
        jSpinnerCreateCellCapacity = new javax.swing.JSpinner();
        jButtonCreateCell = new javax.swing.JButton();
        jButtonDeleteCell = new javax.swing.JButton();
        jButtonUpdateCell = new javax.swing.JButton();
        jLabelSentence = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPrisonerCreateDay = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerPrisonerCreateMonth = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerPrisonerCreateYear = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerPrisonerUpdateDay = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerPrisonerUpdateMonth = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerPrisonerUpdateYear = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerSentenceStardDay = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerSentenceStardMonth = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerSentenceStardYear = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerSentenceEndDay = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerSentenceEndMonth = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerSentenceEndYear = new javax.swing.JSpinner();
        jButtonRefreshAll = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSpinnerUpdateCellCapacity = new javax.swing.JSpinner();
        jComboBoxUpdateCellFloor = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelSentences = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSentences = new javax.swing.JTable();
        jLabelSentences = new javax.swing.JLabel();
        jButtonSentenceDelete = new javax.swing.JButton();
        jComboBoxSentenceUpdatePunishment = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();

        jTablePrisoners.setModel(new PrisonersTableModel());
        jScrollPane2.setViewportView(jTablePrisoners);

        jButtonCreatePrisoner.setText("Create Prisoner");
        jButtonCreatePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreatePrisonerActionPerformed(evt);
            }
        });

        jLabelPrisoners.setText("Prisoners");

        jTextFieldPrisonerCreateName.setText("Create Name");

        jTextFieldPrisonerCreateSurname.setText("Create Surname");

        jButtonDeletePrisoner.setText("Delete Prisoner");
        jButtonDeletePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePrisonerActionPerformed(evt);
            }
        });

        jTextFieldPrisonerUpdateName.setText("Update Name");

        jTextFieldPrisonerUpdateSurname.setText("Update Surname");

        jButtonUpdatePrisoner.setText("Update Prisoner");
        jButtonUpdatePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePrisonerActionPerformed(evt);
            }
        });

        jComboBoxSentencePunishment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCreateSentence.setText("Create Sentence");
        jButtonCreateSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateSentenceActionPerformed(evt);
            }
        });

        jLabelCells.setText("Cells");

        jComboBoxCreateCellFloor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floor 1", "Floor 2", "Floor 3", "Floor 4", "Floor 5" }));
        jComboBoxCreateCellFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCreateCellFloorActionPerformed(evt);
            }
        });

        jTableCells.setModel(new CellsTableModel());
        jScrollPane4.setViewportView(jTableCells);

        jSpinnerCreateCellCapacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jButtonCreateCell.setText("Create Cell");
        jButtonCreateCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCellActionPerformed(evt);
            }
        });

        jButtonDeleteCell.setText("Delete Cell");
        jButtonDeleteCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCellActionPerformed(evt);
            }
        });

        jButtonUpdateCell.setText("Update Cell");
        jButtonUpdateCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCellActionPerformed(evt);
            }
        });

        jLabelSentence.setText("Sentence");

        jLabel1.setText("Capacity:");

        jLabel2.setText("Day");

        jLabel3.setText("Month");

        jLabel4.setText("Year");

        jLabel5.setText("Day");

        jLabel6.setText("Month");

        jLabel7.setText("Year");

        jLabel8.setText("Start Date");

        jLabel9.setText("End Date");

        jLabel10.setText("Day");

        jLabel11.setText("Month");

        jLabel12.setText("Year");

        jLabel13.setText("Day");

        jLabel14.setText("Month");

        jLabel15.setText("Year");

        jButtonRefreshAll.setText("Refresh All");
        jButtonRefreshAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshAllActionPerformed(evt);
            }
        });

        jLabel24.setText("Capacity:");

        jSpinnerUpdateCellCapacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jComboBoxUpdateCellFloor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floor 1", "Floor 2", "Floor 3", "Floor 4", "Floor 5" }));
        jComboBoxUpdateCellFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUpdateCellFloorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrisonersLayout = new javax.swing.GroupLayout(jPanelPrisoners);
        jPanelPrisoners.setLayout(jPanelPrisonersLayout);
        jPanelPrisonersLayout.setHorizontalGroup(
            jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrisonersLayout.createSequentialGroup()
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                .addComponent(jComboBoxUpdateCellFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerUpdateCellCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRefreshAll)
                                .addGap(0, 0, 0))
                            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                        .addComponent(jComboBoxCreateCellFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerCreateCellCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDeleteCell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreateCell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jButtonUpdateCell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCells, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrisoners, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                .addComponent(jTextFieldPrisonerCreateName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrisonerCreateSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPrisonerCreateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPrisonerCreateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPrisonerCreateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrisonersLayout.createSequentialGroup()
                                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrisonersLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPrisonerUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrisonerUpdateSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerPrisonerUpdateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceStardDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceStardMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceStardYear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinnerSentenceEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(0, 15, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerPrisonerUpdateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxSentencePunishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPrisonerUpdateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(81, 81, 81)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeletePrisoner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreatePrisoner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUpdatePrisoner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrisonersLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCreateSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPrisonersLayout.setVerticalGroup(
            jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPrisoners, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrisonerCreateSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrisonerCreateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreatePrisoner)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerPrisonerCreateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerPrisonerCreateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerPrisonerCreateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonDeletePrisoner))
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrisonerUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrisonerUpdateSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdatePrisoner)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerPrisonerUpdateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerPrisonerUpdateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerPrisonerUpdateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerSentenceStardDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jSpinnerSentenceStardMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jSpinnerSentenceStardYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jSpinnerSentenceEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jSpinnerSentenceEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jSpinnerSentenceEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSentencePunishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCreateSentence))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCells, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCreateCellFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerCreateCellCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCreateCell)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButtonDeleteCell)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUpdateCellFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jSpinnerUpdateCellCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateCell)
                    .addComponent(jButtonRefreshAll))
                .addGap(15, 15, 15))
        );

        jTabbedPanePrison.addTab("Prisoners", jPanelPrisoners);

        jTableSentences.setModel(new SentencesTableModel());
        jTableSentences.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTableSentences);
        jTableSentences.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabelSentences.setText("Sentences");

        jButtonSentenceDelete.setText("Delete Sentence");

        jComboBoxSentenceUpdatePunishment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Update Sentence");

        jLabel16.setText("Start Day");

        jLabel17.setText("End Day");

        jLabel18.setText("Day");

        jLabel19.setText("Month");

        jLabel20.setText("Year");

        jLabel21.setText("Day");

        jLabel22.setText("Month");

        jLabel23.setText("Year");

        javax.swing.GroupLayout jPanelSentencesLayout = new javax.swing.GroupLayout(jPanelSentences);
        jPanelSentences.setLayout(jPanelSentencesLayout);
        jPanelSentencesLayout.setHorizontalGroup(
            jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSentencesLayout.createSequentialGroup()
                        .addComponent(jLabelSentences, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSentencesLayout.createSequentialGroup()
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                                .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(37, 37, 37)
                                .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSentencesLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelSentencesLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addComponent(jComboBoxSentenceUpdatePunishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jButtonSentenceDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        jPanelSentencesLayout.setVerticalGroup(
            jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSentences, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSentencesLayout.createSequentialGroup()
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButtonSentenceDelete)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23)
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanelSentencesLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSentenceUpdatePunishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(364, Short.MAX_VALUE))
        );

        jTabbedPanePrison.addTab("Sentences", jPanelSentences);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanePrison)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrison)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreatePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreatePrisonerActionPerformed
        PrisonersTableModel model = (PrisonersTableModel) jTablePrisoners.getModel();
        String name = jTextFieldPrisonerCreateName.getText();
        String surname = jTextFieldPrisonerCreateSurname.getText();
        try {
            int day = (Integer) jSpinnerPrisonerCreateDay.getValue();
            if (day <= 0 || day > 31) {
                JOptionPane.showMessageDialog(null," ENTER VALID DAY ");
                return;
            }
            int month = (Integer) jSpinnerPrisonerCreateMonth.getValue();
            if (month <= 0 || month > 12) {
                JOptionPane.showMessageDialog(null," ENTER VALID MONTH ");
                return;
            }
            int year = (Integer) jSpinnerPrisonerCreateYear.getValue();
            LocalDate born = LocalDate.of(year, month, day);
            Prisoner prisoner = new Prisoner(name, surname, born);
            pM.createPrisoner(prisoner);
            model.addPrisoner(prisoner);
        }
        catch (DateTimeException e) {}
    }//GEN-LAST:event_jButtonCreatePrisonerActionPerformed

    private void jButtonCreateCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCellActionPerformed
        CellsTableModel model = (CellsTableModel) jTableCells.getModel();
        int floor = jComboBoxCreateCellFloor.getSelectedIndex() + 1;
        int capacity = (Integer) jSpinnerCreateCellCapacity.getValue();
        Cell cell = new Cell(floor,capacity);
        cM.createCell(cell);
        model.addCell(cell);
    }//GEN-LAST:event_jButtonCreateCellActionPerformed

    private void jButtonDeleteCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCellActionPerformed
        CellsTableModel model = (CellsTableModel) jTableCells.getModel();
        int rowIndex = jTableCells.getSelectedRow();
        Long id = (Long) model.getValueAt(rowIndex, 0);
        cM.deleteCell(cM.getCellById(id));
        model.deleteCell(rowIndex);
    }//GEN-LAST:event_jButtonDeleteCellActionPerformed

    private void jButtonUpdateCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCellActionPerformed
        CellsTableModel model = (CellsTableModel) jTableCells.getModel();
        int rowIndex = jTableCells.getSelectedRow();
        Long id = (Long) model.getValueAt(rowIndex, 0);
        int floor = jComboBoxUpdateCellFloor.getSelectedIndex() + 1;
        int capacity = (Integer) jSpinnerUpdateCellCapacity.getValue();
        Cell cell = new Cell(floor, capacity);
        cell.setId(id);
        cM.updateCell(cell);
        model.updateCell(cell, rowIndex);
        
    }//GEN-LAST:event_jButtonUpdateCellActionPerformed

    private void jButtonCreateSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateSentenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateSentenceActionPerformed

    private void jButtonUpdatePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePrisonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdatePrisonerActionPerformed

    private void jButtonDeletePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePrisonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeletePrisonerActionPerformed

    private void jComboBoxCreateCellFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCreateCellFloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCreateCellFloorActionPerformed

    private void jButtonRefreshAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshAllActionPerformed
        PrisonersTableModel model_prisoners = (PrisonersTableModel) jTablePrisoners.getModel();
        CellsTableModel model_cells = (CellsTableModel) jTableCells.getModel();
        SentencesTableModel model_sentences = (SentencesTableModel) jTableSentences.getModel();
        model_cells.refresh();
        model_prisoners.refresh();
        model_sentences.refresh();
        addAllCells(model_cells);
        addAllSentences(model_sentences);
        addAllPrisoners(model_prisoners);
    }//GEN-LAST:event_jButtonRefreshAllActionPerformed

    private void jComboBoxUpdateCellFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUpdateCellFloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUpdateCellFloorActionPerformed
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrisonFrame frame = new PrisonFrame();
                frame.setPreferredSize(new Dimension(850, 700));
                frame.getContentPane().add(new PrisonTabbedPane(), BorderLayout.CENTER);
                frame.setDefaultCloseOperation(PrisonFrame.EXIT_ON_CLOSE);
                frame.setTitle("Prison");
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreateCell;
    private javax.swing.JButton jButtonCreatePrisoner;
    private javax.swing.JButton jButtonCreateSentence;
    private javax.swing.JButton jButtonDeleteCell;
    private javax.swing.JButton jButtonDeletePrisoner;
    private javax.swing.JButton jButtonRefreshAll;
    private javax.swing.JButton jButtonSentenceDelete;
    private javax.swing.JButton jButtonUpdateCell;
    private javax.swing.JButton jButtonUpdatePrisoner;
    private javax.swing.JComboBox<String> jComboBoxCreateCellFloor;
    private javax.swing.JComboBox<String> jComboBoxSentencePunishment;
    private javax.swing.JComboBox<String> jComboBoxSentenceUpdatePunishment;
    private javax.swing.JComboBox<String> jComboBoxUpdateCellFloor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCells;
    private javax.swing.JLabel jLabelPrisoners;
    private javax.swing.JLabel jLabelSentence;
    private javax.swing.JLabel jLabelSentences;
    private javax.swing.JPanel jPanelPrisoners;
    private javax.swing.JPanel jPanelSentences;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinnerCreateCellCapacity;
    private javax.swing.JSpinner jSpinnerPrisonerCreateDay;
    private javax.swing.JSpinner jSpinnerPrisonerCreateMonth;
    private javax.swing.JSpinner jSpinnerPrisonerCreateYear;
    private javax.swing.JSpinner jSpinnerPrisonerUpdateDay;
    private javax.swing.JSpinner jSpinnerPrisonerUpdateMonth;
    private javax.swing.JSpinner jSpinnerPrisonerUpdateYear;
    private javax.swing.JSpinner jSpinnerSentenceEndDay;
    private javax.swing.JSpinner jSpinnerSentenceEndMonth;
    private javax.swing.JSpinner jSpinnerSentenceEndYear;
    private javax.swing.JSpinner jSpinnerSentenceStardDay;
    private javax.swing.JSpinner jSpinnerSentenceStardMonth;
    private javax.swing.JSpinner jSpinnerSentenceStardYear;
    private javax.swing.JSpinner jSpinnerUpdateCellCapacity;
    private javax.swing.JTabbedPane jTabbedPanePrison;
    private javax.swing.JTable jTableCells;
    private javax.swing.JTable jTablePrisoners;
    private javax.swing.JTable jTableSentences;
    private javax.swing.JTextField jTextFieldPrisonerCreateName;
    private javax.swing.JTextField jTextFieldPrisonerCreateSurname;
    private javax.swing.JTextField jTextFieldPrisonerUpdateName;
    private javax.swing.JTextField jTextFieldPrisonerUpdateSurname;
    // End of variables declaration//GEN-END:variables
}
