
package cz.muni.fi.pv168.swing;

import java.awt.BorderLayout;
import java.time.LocalDate;

/**
 *
 * @author Zita
 */
public class PrisonFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrisonFrame
     */
    public PrisonFrame() {
        initComponents();

        PrisonersTableModel model_prisoners = (PrisonersTableModel) jTablePrisoners.getModel();
        model_prisoners.addPrisoner(new Prisoner(1, "Martin", "Panak", LocalDate.of(1964, 3, 1)));
        
        SentencesTableModel model_sentences = (SentencesTableModel) jTableSentences.getModel();
        model_sentences.addSentence(new Sentence(1, 2, LocalDate.of(2015, 1, 3), LocalDate.of(2016, 4, 5), "murderer"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPanePrison = new javax.swing.JTabbedPane();
        jPanelPrisoners = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePrisoners = new javax.swing.JTable();
        jButtonAddPrisoner = new javax.swing.JButton();
        jPanelSentences = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSentences = new javax.swing.JTable();
        jButtonAddSentence = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("tab1", jScrollPane1);

        jTablePrisoners.setModel(new PrisonersTableModel());
        jScrollPane2.setViewportView(jTablePrisoners);

        jButtonAddPrisoner.setText("Add Prisoner");
        jButtonAddPrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPrisonerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrisonersLayout = new javax.swing.GroupLayout(jPanelPrisoners);
        jPanelPrisoners.setLayout(jPanelPrisonersLayout);
        jPanelPrisonersLayout.setHorizontalGroup(
            jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                .addComponent(jButtonAddPrisoner)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPrisonersLayout.setVerticalGroup(
            jPanelPrisonersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrisonersLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddPrisoner)
                .addContainerGap())
        );

        jTabbedPanePrison.addTab("Prisoners", jPanelPrisoners);

        jTableSentences.setModel(new SentencesTableModel());
        jScrollPane3.setViewportView(jTableSentences);

        jButtonAddSentence.setText("Add Sentence");
        jButtonAddSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSentenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSentencesLayout = new javax.swing.GroupLayout(jPanelSentences);
        jPanelSentences.setLayout(jPanelSentencesLayout);
        jPanelSentencesLayout.setHorizontalGroup(
            jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                .addComponent(jButtonAddSentence)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelSentencesLayout.setVerticalGroup(
            jPanelSentencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSentencesLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddSentence)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTabbedPanePrison.addTab("Sentences", jPanelSentences);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrison)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrison, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPrisonerActionPerformed
        PrisonersTableModel model_prisoners = (PrisonersTableModel) jTablePrisoners.getModel();
        model_prisoners.addPrisoner(newPrisoner());
    }//GEN-LAST:event_jButtonAddPrisonerActionPerformed

    private void jButtonAddSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSentenceActionPerformed
        SentencesTableModel model_sentences = (SentencesTableModel) jTableSentences.getModel();
        model_sentences.addSentence(newSentence());
    }//GEN-LAST:event_jButtonAddSentenceActionPerformed
   
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrisonFrame frame = new PrisonFrame();
                frame.getContentPane().add(new PrisonTabbedPane(), BorderLayout.CENTER);
                frame.setDefaultCloseOperation(PrisonFrame.EXIT_ON_CLOSE);
                frame.setTitle("Prison");
                frame.setVisible(true);
            }
        });
    }
    
    private Prisoner newPrisoner() {
        return null;
    }
    
    private Sentence newSentence() {
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPrisoner;
    private javax.swing.JButton jButtonAddSentence;
    private javax.swing.JPanel jPanelPrisoners;
    private javax.swing.JPanel jPanelSentences;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPanePrison;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePrisoners;
    private javax.swing.JTable jTableSentences;
    // End of variables declaration//GEN-END:variables
}
